[package]
name = "code-to-md"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
dirs = "6.0.0"
eframe = { version = "0.36.1", features = ["persistence"] }
egui = "0.36.1"
ignore = "0.4.33"
rfd = "0.17.2"
serde = { version = "1.0", features = ["derive"] }
image = { version = "0.25", default-features = false, features = ["ico"] }
syntect = { version = "5.2", default-features = false, features = ["default-syntaxes", "default-themes", "regex-fancy"] }

[build-dependencies]
winres = "0.1"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
panic = "abort"
